import React from "react";
import CrimeTable from "./CrimeTable";
import { missionSteps } from "../data";

export default function Mission({ sector, identity, missionLevel, step, setStep, anomalies, setAnomalies, selectedAnswer, setSelectedAnswer, notify, onFinish }) {
    const toggleAnomaly = issue => {
        setAnomalies(a => a.includes(issue) ? a.filter(x => x !== issue) : [...a, issue]);
    };
    const next = () => setStep(Math.min(6, step + 1));
    const back = () => setStep(Math.max(0, step - 1));
    return React.createElement("main", { className: "page" },
        React.createElement("div", { className: "mission-header" },
            React.createElement("div", { className: "mission-title" },
                React.createElement("div", { className: "eyebrow" },
                    sector.name,
                    " \u2022 Mission 01"),
                React.createElement("h2", null, "The West District Spike"),
                React.createElement("p", null, "Determine whether a dramatic increase in vehicle theft reports is real\u2014and what the city should do next.")),
            React.createElement("div", { className: "card soft", style: { minWidth: 210 } },
                React.createElement("div", { className: "level" }, "MISSION STATUS"),
                React.createElement("b", null, missionSteps[step]),
                React.createElement("div", { style: { fontSize: 12, color: "var(--muted)", marginTop: 5 } },
                    missionLevel,
                    " \u2022 ",
                    identity.role))),
        React.createElement("div", { className: "stepper" }, missionSteps.map((s, i) => React.createElement("div", { className: "step " + (i === step ? "active" : i < step ? "done" : ""), key: s },
            i < step ? "✓ " : i + 1 + ". ",
            s))),
        step === 0 && React.createElement("div", { className: "grid cols-3" },
            React.createElement("div", { className: "card", style: { gridColumn: "span 2" } },
                React.createElement("div", { className: "eyebrow" }, "Mission Briefing"),
                React.createElement("h2", null, "Command wants an answer before tomorrow morning."),
                React.createElement("p", { style: { color: "var(--muted)", lineHeight: 1.7 } }, "Vehicle theft reports appear to have surged in the West District. The police chief is considering moving officers from other districts. Before resources are reassigned, your job is to determine whether the data supports the claim."),
                React.createElement("div", { className: "callout" },
                    React.createElement("b", null, "Your responsibility:"),
                    " Do not assume the dataset is correct. Inspect the evidence before calculating or recommending anything.")),
            React.createElement("div", { className: "card beacon" },
                React.createElement("div", { className: "beacon-orb" }, "\u2600\uFE0F"),
                React.createElement("div", { className: "beacon-copy" },
                    React.createElement("h3", null, "Beacon"),
                    React.createElement("p", null, "\u201CAnalysts don't start with the answer. They start by asking whether the data can be trusted.\u201D")))),
        step === 1 && React.createElement("div", { className: "card" },
            React.createElement("div", { className: "section-title" },
                React.createElement("div", null,
                    React.createElement("div", { className: "eyebrow" }, "Data Lab"),
                    React.createElement("h2", null, "Inspect the raw incident data"),
                    React.createElement("p", null, "Look before you calculate. Something here may distort the entire analysis."))),
            React.createElement(CrimeTable, { interactive: false }),
            React.createElement("div", { className: "callout", style: { marginTop: 14 } }, "Beacon hint: Compare values within each column. Look for values that are missing, repeated, inconsistent, or unusually large.")),
        step === 2 && React.createElement("div", { className: "card" },
            React.createElement("div", { className: "section-title" },
                React.createElement("div", null,
                    React.createElement("div", { className: "eyebrow" }, "Find the Signal"),
                    React.createElement("h2", null, "Flag the issues you believe require investigation"),
                    React.createElement("p", null, "Select all that apply.")),
                React.createElement("div", null,
                    React.createElement("span", { className: "tag" },
                        anomalies.length,
                        " FLAGGED"))),
            React.createElement("div", { className: "grid cols-4", style: { marginBottom: 14 } }, [
                ["outlier", "510 calls in West", "Possible outlier or data-entry error"],
                ["missing", "Missing arrest value", "Incomplete field"],
                ["duplicate", "Repeated incident S-1045", "Potential duplicate record"],
                ["category", "“veh theft” category", "Inconsistent coding"]
            ].map(([id, h, p]) => React.createElement("button", { key: id, className: "answer " + (anomalies.includes(id) ? "selected" : ""), onClick: () => toggleAnomaly(id) },
                React.createElement("b", null, h),
                React.createElement("br", null),
                React.createElement("span", { style: { color: "var(--muted)", fontSize: 12 } }, p)))),
            React.createElement(CrimeTable, { interactive: true })),
        step === 3 && React.createElement("div", { className: "grid cols-3" },
            React.createElement("div", { className: "card question-card", style: { gridColumn: "span 2" } },
                React.createElement("div", { className: "eyebrow" }, "Build the Evidence"),
                React.createElement("h3", null, "After verifying the West District value should be 56 calls, which comparison is most appropriate?"),
                React.createElement("p", { style: { color: "var(--muted)" } }, "District populations are different. Choose the measure that best supports a fair comparison."),
                React.createElement("div", { className: "answers" }, [
                    ["a", "Compare total calls only"],
                    ["b", "Compare vehicle theft calls per 1,000 residents"],
                    ["c", "Compare the number of arrests only"],
                    ["d", "Compare district population only"]
                ].map(([id, t]) => React.createElement("button", { key: id, className: "answer " + (selectedAnswer === id ? "selected" : ""), onClick: () => setSelectedAnswer(id) }, t))),
                selectedAnswer && React.createElement("div", { className: "callout", style: { marginTop: 12, borderLeftColor: selectedAnswer === "b" ? "var(--good)" : "var(--warn)" } }, selectedAnswer === "b" ? React.createElement(React.Fragment, null,
                    React.createElement("b", null, "Strong choice."),
                    " A population-adjusted rate provides a fairer comparison across districts.") : React.createElement(React.Fragment, null,
                    React.createElement("b", null, "Reconsider the denominator."),
                    " A raw count can be misleading when population sizes differ."))),
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Quant Skills"),
                React.createElement("h3", null, "This mission combines:"),
                React.createElement("p", { className: "tag" }, "Data Quality"),
                React.createElement("p", { className: "tag" }, "Rates"),
                React.createElement("p", { className: "tag" }, "Percent Change"),
                React.createElement("p", { className: "tag" }, "Comparative Reasoning"))),
        step === 4 && React.createElement("div", { className: "assessment" },
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Make the Call"),
                React.createElement("h2", null, "What should command staff do?"),
                React.createElement("p", { style: { color: "var(--muted)" } }, "Verified rates show the West District is somewhat elevated, but nowhere near the apparent 10\u00D7 spike in the raw dataset."),
                React.createElement("div", { className: "answers" }, [
                    ["Deploy a large permanent patrol increase immediately", "High-cost action based on limited evidence."],
                    ["Run a targeted 30-day response and continue monitoring", "Proportional response while gathering stronger evidence."],
                    ["Take no action", "Ignores a smaller but potentially meaningful pattern."],
                ].map(([h, p]) => React.createElement("button", { className: "answer", key: h, onClick: () => notify("Decision recorded in your Case Brief.") },
                    React.createElement("b", null, h),
                    React.createElement("br", null),
                    React.createElement("span", { style: { color: "var(--muted)", fontSize: 12 } }, p))))),
            React.createElement("div", { className: "card beacon" },
                React.createElement("div", { className: "beacon-orb" }, "\u2600\uFE0F"),
                React.createElement("div", { className: "beacon-copy" },
                    React.createElement("h3", null, "Beacon Challenge"),
                    React.createElement("p", null, "\u201CThe police chief asks: If the spike wasn't real, why take any action at all? Your recommendation needs to distinguish bad data from a potentially real underlying pattern.\u201D")))),
        step === 5 && React.createElement("div", { className: "assessment" },
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Final Mission Assessment"),
                React.createElement("h2", null, "Case Brief"),
                React.createElement("p", { style: { color: "var(--muted)" } }, "Your assessment is based on the quality of your reasoning\u2014not just whether you selected a preferred option."),
                React.createElement("div", { className: "rubric" }, [
                    ["Identifies and validates data-quality issues", "4 / 4"],
                    ["Selects appropriate quantitative measures", "4 / 4"],
                    ["Uses evidence accurately", "3 / 4"],
                    ["Acknowledges uncertainty and limitations", "3 / 4"],
                    ["Defends a proportional recommendation", "4 / 4"]
                ].map(([a, b]) => React.createElement("div", { className: "rubric-row", key: a },
                    React.createElement("div", null, a),
                    React.createElement("div", { className: "score-chip" }, b))))),
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Mission Result"),
                React.createElement("h2", { style: { fontSize: 48, margin: "10px 0" } }, "18 / 20"),
                React.createElement("p", null,
                    React.createElement("b", null, "Strongest:"),
                    " Data Quality + Rates"),
                React.createElement("p", null,
                    React.createElement("b", null, "Developing:"),
                    " Explaining uncertainty"),
                React.createElement("p", null,
                    React.createElement("b", null, "Credential progress:"),
                    " Signal Finder 3/3"),
                React.createElement("div", { className: "progress" },
                    React.createElement("div", { style: { width: "92%" } })))),
        step === 6 && React.createElement("div", { className: "assessment" },
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Beacon Debrief"),
                React.createElement("h2", null, "Think about how you reasoned."),
                React.createElement("div", { className: "answers" },
                    React.createElement("button", { className: "answer" }, "What evidence most influenced your decision?"),
                    React.createElement("button", { className: "answer" }, "Which calculation or comparison were you least confident about?"),
                    React.createElement("button", { className: "answer" }, "What would you investigate next if you had more time?"))),
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Identity Growth"),
                React.createElement("h3", null, "Mission rewards"),
                React.createElement("p", null, "+85 Nexus Reputation"),
                React.createElement("p", null, "+1 Sentinel Clearance"),
                React.createElement("p", null,
                    "Credential earned: ",
                    React.createElement("span", { className: "tag" }, "SIGNAL FINDER")),
                React.createElement("p", null,
                    "Beacon Trust increased to ",
                    React.createElement("b", null, "Level 3"),
                    "."),
                React.createElement("button", { className: "btn good", style: { marginTop: 14 }, onClick: onFinish }, "VIEW UPDATED IDENTITY \u2192"))),
        React.createElement("div", { style: { display: "flex", justifyContent: "space-between", marginTop: 18 } },
            React.createElement("button", { className: "btn secondary", disabled: step === 0, onClick: back }, "\u2190 BACK"),
            step < 6 && React.createElement("button", { className: "btn", onClick: next }, "NEXT \u2192")));
}
