import React, { useState } from "react";
import AssessmentVisual from "./AssessmentVisual";
import { majors, preAttitudeStatements, preCognitiveQuestions } from "../data";

export default function PreAssessment({identity,onComplete,onExit}) {
  const [part,setPart]=useState(1), [info,setInfo]=useState({name:identity.name||"",studentId:"",instructor:identity.faculty||"",date:new Date().toLocaleDateString()}), [att,setAtt]=useState({}), [cog,setCog]=useState({}), [demo,setDemo]=useState({majors:[]}), [showSkillsRecap,setShowSkillsRecap]=useState(false);
  const attitudeComplete=preAttitudeStatements.every((_,i)=>att[i]);
  const cognitiveComplete=preCognitiveQuestions.every((_,i)=>cog[i]!==undefined);
  const score=preCognitiveQuestions.reduce((n,q,i)=>n+(cog[i]===q.a?1:0),0), pct=Math.round(score/20*100), band=pct>=80?"Advanced":pct>=60?"Intermediate":"Beginner";
  const requiredDemo=["gender","race","citizen","englishFirst","bornOutsideUS","otherLanguageHome","firstGen","parentEducation","income","financialAid","birthYear","collegeGrade","mathGrade","credits","accommodations","email","phone"];
  const demoComplete=requiredDemo.every(k=>demo[k]!==undefined&&String(demo[k]).trim()!=="")&&demo.majors.length>0;
  const setD=(k,v)=>setDemo({...demo,[k]:v}), toggleMajor=m=>setDemo({...demo,majors:demo.majors.includes(m)?demo.majors.filter(x=>x!==m):[...demo.majors,m]});
  const skillStats={};preCognitiveQuestions.forEach((q,i)=>{if(!skillStats[q.skill])skillStats[q.skill]={right:0,total:0};skillStats[q.skill].total++;if(cog[i]===q.a)skillStats[q.skill].right++;});
  const progress=React.createElement("div",{className:"preassess-progress"},[1,2,3].map(n=>React.createElement("div",{key:n,className:"seg "+(part===n?"active":part>n?"done":"")},n===1?"Part 1 · Attitudes":n===2?"Part 2 · Skills":"Part 3 · Background")));

  if(showSkillsRecap) return React.createElement("main",{className:"page"},React.createElement("div",{className:"preassess-shell"},
    React.createElement("div",{className:"preassess-header"},React.createElement("div",{className:"eyebrow"},"Pre-Assessment · Part 2 Complete"),React.createElement("h2",null,"Quantitative Skills Recap"),React.createElement("p",null,"This is a baseline snapshot of your current skills. It does not affect your standing in SHINE.")),
    progress,
    React.createElement("div",{className:"score-hero"},
      React.createElement("div",{className:"score-box"},React.createElement("div",{className:"score-number"},score,"/20"),React.createElement("div",{className:"score-band"},band),React.createElement("div",{className:"score-copy"},pct+"% correct. This level summarizes your starting point before entering a Scalaris Sector.")),
      React.createElement("div",{className:"score-box"},React.createElement("div",{className:"sprint-result-label"},"Skill Breakdown"),React.createElement("div",{className:"skill-breakdown"},Object.entries(skillStats).map(([k,v])=>{const p=Math.round(v.right/v.total*100);return React.createElement("div",{className:"skill-breakdown-row",key:k},React.createElement("div",null,k),React.createElement("div",{className:"skill-breakdown-track"},React.createElement("span",{style:{width:p+"%"}})),React.createElement("div",null,p+"%"));})))) ,
    React.createElement("div",{className:"callout"},React.createElement("strong",null,"Prototype performance bands"),React.createElement("div",{style:{marginTop:5,color:"var(--muted)",fontSize:"13px"}},"Beginner: 0–59% • Intermediate: 60–79% • Advanced: 80–100%. The source assessment does not define these cut points; they are used here as the Scalaris prototype rule.")),
    React.createElement("div",{className:"assessment-nav"},React.createElement("button",{className:"btn secondary",onClick:()=>setShowSkillsRecap(false)},"← REVIEW PART 2"),React.createElement("button",{className:"btn",onClick:()=>{setPart(3);setShowSkillsRecap(false);window.scrollTo({top:0,behavior:"smooth"});}},"CONTINUE TO PART 3 →"))
  ));

  return React.createElement("main",{className:"page"},React.createElement("div",{className:"preassess-shell"},
    React.createElement("div",{className:"preassess-header"},React.createElement("div",{className:"eyebrow"},"Required Before Sector Access"),React.createElement("h2",null,"HSI-SHINE Baseline Pre-Assessment"),React.createElement("p",null,"Complete all three parts before entering any Sector. Part 2 may use a calculator or spreadsheet, but not artificial intelligence to look up answers.")),progress,

    part===1&&React.createElement(React.Fragment,null,
      React.createElement("div",{className:"card"},React.createElement("h3",{style:{marginTop:0}},"Participant Information"),React.createElement("div",{className:"form-row"},
        React.createElement("div",null,React.createElement("label",null,"Name"),React.createElement("input",{value:info.name,onChange:e=>setInfo({...info,name:e.target.value})})),
        React.createElement("div",null,React.createElement("label",null,"Student ID"),React.createElement("input",{value:info.studentId,onChange:e=>setInfo({...info,studentId:e.target.value})})),
        React.createElement("div",null,React.createElement("label",null,"Instructor Name / Mentor"),React.createElement("input",{value:info.instructor,onChange:e=>setInfo({...info,instructor:e.target.value})})),
        React.createElement("div",null,React.createElement("label",null,"Date"),React.createElement("input",{value:info.date,onChange:e=>setInfo({...info,date:e.target.value})}))),
        React.createElement("div",{className:"callout",style:{marginTop:16}},React.createElement("strong",null,"Assessment notice"),React.createElement("div",{style:{marginTop:5,color:"var(--muted)",fontSize:"13px"}},"This assessment is required for SHINE participants and is also used for research purposes by the SHINE project leadership team. Students who wish to participate in the SHINE Research Program must complete the Institutional Review Board (IRB) consent form before completing this assessment."))),
      React.createElement("div",{className:"card",style:{marginTop:16}},React.createElement("h3",{style:{marginTop:0}},"Part 1: Attitudinal Questions"),React.createElement("p",{style:{color:"var(--muted)",fontSize:"13px"}},"Use the same 1–7 scale for every statement."),preAttitudeStatements.map((s,i)=>React.createElement("div",{className:"assessment-question",key:i},React.createElement("h4",null,(i+1)+". "+s),React.createElement("div",{className:"likert-row"},[1,2,3,4,5,6,7].map(v=>React.createElement("button",{key:v,className:"likert-btn "+(att[i]===v?"selected":""),onClick:()=>setAtt({...att,[i]:v})},v))),React.createElement("div",{className:"likert-anchors"},React.createElement("span",null,"1 · Disagree strongly"),React.createElement("span",null,"7 · Agree strongly"))))),
      React.createElement("div",{className:"assessment-nav"},React.createElement("button",{className:"btn secondary",onClick:onExit},"RETURN TO NEXUS"),React.createElement("button",{className:"btn",disabled:!attitudeComplete,style:{opacity:attitudeComplete?1:.45},onClick:()=>{setPart(2);window.scrollTo({top:0,behavior:"smooth"});}},"CONTINUE TO PART 2 →"))
    ),

    part===2&&React.createElement(React.Fragment,null,
      React.createElement("div",{className:"card"},React.createElement("h3",{style:{marginTop:0}},"Part 2: Cognitive Questions"),React.createElement("p",{style:{color:"var(--muted)",fontSize:"13px",lineHeight:1.55}},"Select the best answer for each question. This portion measures baseline quantitative reasoning skills and does not affect your standing in SHINE."),preCognitiveQuestions.map((q,i)=>React.createElement("div",{className:"assessment-question",key:i},React.createElement("h4",null,(i+1)+". "+q.q),q.visual&&React.createElement(AssessmentVisual,{type:q.visual}),React.createElement("div",{className:"mc-grid"},q.opts.map((o,oi)=>React.createElement("button",{key:oi,className:"mc-btn "+(cog[i]===oi?"selected":""),onClick:()=>setCog({...cog,[i]:oi})},String.fromCharCode(65+oi)+". "+o)))))),
      React.createElement("div",{className:"assessment-nav"},React.createElement("button",{className:"btn secondary",onClick:()=>{setPart(1);window.scrollTo({top:0,behavior:"smooth"});}},"← PART 1"),React.createElement("button",{className:"btn gold",disabled:!cognitiveComplete,style:{opacity:cognitiveComplete?1:.45},onClick:()=>{setShowSkillsRecap(true);window.scrollTo({top:0,behavior:"smooth"});}},"VIEW SKILLS RECAP →"))
    ),

    part===3&&React.createElement(React.Fragment,null,
      React.createElement("div",{className:"card"},React.createElement("h3",{style:{marginTop:0}},"Part 3: Socio-Demographic Questions"),React.createElement("div",{className:"demo-grid"},
        React.createElement("div",null,React.createElement("label",null,"1. What is your sex/gender?"),React.createElement("input",{value:demo.gender||"",onChange:e=>setD("gender",e.target.value)})),
        React.createElement("div",null,React.createElement("label",null,"2. Racial/ethnic group (pick one)"),React.createElement("select",{value:demo.race||"",onChange:e=>setD("race",e.target.value)},React.createElement("option",{value:""},"Select…"),["Asian or Pacific Islander","Black/African American","Hispanic or Latina/Latino/Latinx","Native American, Alaskan Native, Aleut","White/Caucasian"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"3. US citizen or permanent resident?"),React.createElement("select",{value:demo.citizen||"",onChange:e=>setD("citizen",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"4. Is English your first language or a first language?"),React.createElement("select",{value:demo.englishFirst||"",onChange:e=>setD("englishFirst",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"5. Were you born outside the United States?"),React.createElement("select",{value:demo.bornOutsideUS||"",onChange:e=>setD("bornOutsideUS",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"6. Do you speak a language other than English at home?"),React.createElement("select",{value:demo.otherLanguageHome||"",onChange:e=>setD("otherLanguageHome",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"7. Are you a first-generation student?"),React.createElement("select",{value:demo.firstGen||"",onChange:e=>setD("firstGen",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"8. Highest parent/guardian education"),React.createElement("select",{value:demo.parentEducation||"",onChange:e=>setD("parentEducation",e.target.value)},React.createElement("option",{value:""},"Select…"),["Some High School","High School Graduate","Some College","Associate's Degree or Community College Degree","Bachelor's Degree or Four-Year College Degree","Some Graduate School","Graduate Degree (master's, doctorate, etc.)"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"9. Current household income"),React.createElement("select",{value:demo.income||"",onChange:e=>setD("income",e.target.value)},React.createElement("option",{value:""},"Select…"),["Less than $20,000","$20,000 to $29,999","$30,000 to $39,999","$40,000 to $59,999","$60,000 to $79,999","$80,000 to $100,000","Above $100,000"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"10. Do you currently receive financial aid?"),React.createElement("select",{value:demo.financialAid||"",onChange:e=>setD("financialAid",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"No"),React.createElement("option",null,"Yes"))),
        React.createElement("div",null,React.createElement("label",null,"11. What year were you born?"),React.createElement("select",{value:demo.birthYear||"",onChange:e=>setD("birthYear",e.target.value)},React.createElement("option",{value:""},"Select…"),Array.from({length:80},(_,i)=>new Date().getFullYear()-i).map(y=>React.createElement("option",{key:y},y)))),
        React.createElement("div",null,React.createElement("label",null,"13. Average college grade (or high school grade if first semester)"),React.createElement("select",{value:demo.collegeGrade||"",onChange:e=>setD("collegeGrade",e.target.value)},React.createElement("option",{value:""},"Select…"),["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"14. Average grade in math/statistics courses"),React.createElement("select",{value:demo.mathGrade||"",onChange:e=>setD("mathGrade",e.target.value)},React.createElement("option",{value:""},"Select…"),["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"15. College credits earned to date"),React.createElement("select",{value:demo.credits||"",onChange:e=>setD("credits",e.target.value)},React.createElement("option",{value:""},"Select…"),["0 to 30","31 to 60","61 to 90","91 and above"].map(x=>React.createElement("option",{key:x},x)))),
        React.createElement("div",null,React.createElement("label",null,"16. Do you receive disability accommodations at your college/university?"),React.createElement("select",{value:demo.accommodations||"",onChange:e=>setD("accommodations",e.target.value)},React.createElement("option",{value:""},"Select…"),React.createElement("option",null,"Yes"),React.createElement("option",null,"No"))),
        React.createElement("div",null,React.createElement("label",null,"17. Follow-up email address"),React.createElement("input",{type:"email",value:demo.email||"",onChange:e=>setD("email",e.target.value)})),
        React.createElement("div",null,React.createElement("label",null,"18. Follow-up phone number"),React.createElement("input",{value:demo.phone||"",onChange:e=>setD("phone",e.target.value)}))
      ),React.createElement("div",{className:"assessment-question"},React.createElement("h4",null,"12. What is your current major? Select all that apply."),React.createElement("div",{className:"checkbox-grid"},majors.map(m=>React.createElement("button",{key:m,className:"option-chip "+(demo.majors.includes(m)?"selected":""),onClick:()=>toggleMajor(m)},m))))),
      React.createElement("div",{className:"assessment-nav"},React.createElement("button",{className:"btn secondary",onClick:()=>{setShowSkillsRecap(true);window.scrollTo({top:0,behavior:"smooth"});}},"← SKILLS RECAP"),React.createElement("button",{className:"btn good",disabled:!demoComplete,style:{opacity:demoComplete?1:.45},onClick:()=>onComplete({info,attitudes:att,cognitive:cog,score,pct,band,demographics:demo})},"COMPLETE PRE-ASSESSMENT & UNLOCK SECTORS"))
    )
  ));
}
