import React from "react";
import AssessmentIndicators from "./AssessmentIndicators";

export default function Profile({ identity, onNexus, onReplay, preAssessmentComplete, postAssessmentComplete, projectAssessmentComplete, completedSectors, onPostAssessment }) {
    const skills = [
        ["Data Quality", 92], ["Percent Reasoning", 78], ["Rates & Ratios", 84], ["Statistical Reasoning", 66],
        ["Graph Interpretation", 74], ["Quantitative Argument", 71]
    ];
    return React.createElement("main", { className: "page" },
        React.createElement("div", { className: "section-title" },
            React.createElement("div", null,
                React.createElement("div", { className: "eyebrow" }, "Identity Updated"),
                React.createElement("h2", null, identity.name),
                React.createElement("p", null, "Your Scalaris identity grows through demonstrated reasoning, responsibility, and transfer."))),
        React.createElement("div", { className: "assessment" },
            React.createElement("div", { className: "card" },
                React.createElement("div", { style: { display: "flex", gap: 18, alignItems: "center" } },
                    React.createElement("div", { style: { fontSize: 84 } }, identity.avatar),
                    React.createElement("div", null,
                        React.createElement("div", { className: "eyebrow" }, "Sentinel Sector"),
                        React.createElement("h2", { style: { margin: "5px 0" } }, "Senior Crime Analyst"),
                        React.createElement("p", { style: { color: "var(--muted)" } }, "Nexus Level 8 \u2022 705 Reputation \u2022 Beacon Trust 3"))),
                React.createElement("div", { className: "stat-row", style: { marginTop: 14 } },
                    React.createElement("div", { className: "stat" },
                        React.createElement("b", null, "4"),
                        React.createElement("span", null, "SECTORS OPEN")),
                    React.createElement("div", { className: "stat" },
                        React.createElement("b", null, "3"),
                        React.createElement("span", null, "CREDENTIALS")),
                    React.createElement("div", { className: "stat" },
                        React.createElement("b", null, "2"),
                        React.createElement("span", null, "NEXUS MISSIONS"))),
                React.createElement("h3", { style: { marginTop: 20 } }, "New Unlocks"),
                React.createElement("p", null,
                    React.createElement("span", { className: "tag" }, "Advanced Data Lab"),
                    " ",
                    React.createElement("span", { className: "tag" }, "Sentinel Mission 02"),
                    " ",
                    React.createElement("span", { className: "tag" }, "Signal Finder Credential")),
                React.createElement(AssessmentIndicators, { preAssessmentComplete, postAssessmentComplete, projectAssessmentComplete, allSectorsComplete: completedSectors.length === sectors.length, completedCount: completedSectors.length, totalSectors: sectors.length, onPostAssessment })),
            React.createElement("div", { className: "card" },
                React.createElement("div", { className: "eyebrow" }, "Quantitative Reasoning Profile"),
                React.createElement("div", { className: "skill-list", style: { marginTop: 16 } }, skills.map(([name, val]) => React.createElement("div", { className: "skill-item", key: name },
                    React.createElement("span", null, name),
                    React.createElement("div", { className: "progress" },
                        React.createElement("div", { style: { width: val + "%" } })),
                    React.createElement("b", null, val)))))),
        React.createElement("div", { className: "card", style: { marginTop: 18 } },
            React.createElement("div", { className: "eyebrow" }, "Next Identity Goal"),
            React.createElement("h2", null, "Earn a Cross-Sector Evidence Credential"),
            React.createElement("p", { style: { color: "var(--muted)" } }, "Complete one mission in Vitalis or Terra using data quality + rate reasoning to demonstrate transfer across contexts."),
            React.createElement("div", { className: "cta-row", style: { justifyContent: "flex-start" } },
                React.createElement("button", { className: "btn", onClick: onNexus }, "RETURN TO THE NEXUS"),
                React.createElement("button", { className: "btn secondary", onClick: onReplay }, "REPLAY MISSION"))));
}
